### ISSUE TITLE
Usage documentation not clear

### ISSUE THREAD

**Issue by luigizhou** [evertrue/pam-cookbook#3]
I'm trying to use this cookbook for the management of some service configuration under pam.d, but it's not clear how to use it.

I also tried to run the cookbook without as is, but it throws the following error

NoMethodError
-------------
undefined method `each' for nil:NilClass

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/pam/recipes/default.rb:22:in `from_file'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:336:in `load_recipe'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/pam/recipes/default.rb:

 15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 16:  # See the License for the specific language governing permissions and
 17:  # limitations under the License.
 18:  #
 19:
 20:  Chef::Log.info "Services: #{node['pam_d'].inspect}"
 21:
 22>> node['pam_d']['services'].each do |service, conf|
 23:    template "/etc/pam.d/#{service}" do
 24:      source 'service.erb'
 25:      owner  'root'
 26:      group  'root'
 27:      mode   0644
 28:      variables(
 29:        conf_lines: conf['main'],
 30:        includes: conf['includes']
 31:      )

Platform:
---------
x86_64-linux

**Comment by jeffbyrnes** [comment]
@luigizhou you state `x86_64-linux` as your platform but, well, it’s not, in terms of Chef’s concept of a `platform` and `platform_family`. That would be your chip architecture.

Based on the [default for `node['pam_d']['services']`](https://github.com/evertrue/pam-cookbook/blob/master/attributes/default.rb#L1-L2), I suspect you are not operating a Debian `platform_family` system. You’ll note that the attribute only has value if you’re on a Debian-esque system (Debian itself, Ubuntu, etc.).

So, if you’re using Amazon Linux, or CentOS, or another Red Hat EL-based system, that attribute will have no value, and thus you’ll see the error you received.

That, of course, means that the `README` [is a liar](https://github.com/evertrue/pam-cookbook#supported-platforms), but I lack contributor rights nowadays & can’t fix that. @eherot?

For the moment, a workaround would be to `node.override['pam_d']['services']` with values that make sense for your system(s), using a wrapper cookbook.

**Comment by eherot** [comment]
Derp. Ok I'll fix the docs now and leave this issue open until I can add RedHat support. PR's accepted of course!

**Comment by eherot** [comment]
So in retrospect I don't think the problem was so much a lack of support for non-Ubuntu systems as it was that the default recipe just didn't gracefully handle a condition wherein no services were defined (which is a perfectly legitimate if somewhat useless situation).

**Comment by eherot** [comment]
So @luigizhou in case it's not clear in the docs, the main thing you would need to do to make this cookbook work is to define any pam modules you'd like to create using the `node['pam_d']['services']` attribute hash.

If you could let me know exactly what it is you're trying to achieve perhaps I can walk you through what you need to do...

**Comment by luigizhou** [comment]
Hi @eherot thank you for the offer but in the end I created a more custom cookbook, as I had other configurations file outside the pam.d folder to manage.

I guess you can now close the issue?
